filters:
  '*.css':
    - uglifycss
    - compress deflate:
        level: 9

  '*.html':
    - html-minifier
    - compress deflate:
        level: 9

  '*.js':
    - compress deflate:
        level: 9

  '*.svg':
    - compress deflate:
        level: 9

  '*.woff*':
    - no compress

  '*':
    - compress heatshrink:
        window: 11
        lookahead: 4
