filters:
  '*.css':
    - uglifycss

  '*.html':
    - html-minifier
    - compress deflate:
        level: 9

  '*.js':
    - babel-convert
    - uglify-js

  '*.woff*':
    - no compress

  '*':
    - compress heatshrink:
        window: 11
        lookahead: 4
